"""
Re-import the plant asset tree from the normalized IJP export
(all_ijps_normalized_exports/structure) into the CPIIS schema.

The export is flat: area -> section -> equipment -> check tasks (no parts).
To preserve the app pipeline (activity -> part -> equipment), we map:
  - each equipment  -> one equipment_part "MAIN" (the machine as a whole)
  - each equipment  -> one general inspection_activity whose standard_checklist
                       is the list of that equipment's check tasks.

Emits scripts/data/seed-new-structure.sql (idempotent-ish; run after TRUNCATE).
Run:  python scripts/import_new_structure.py
"""
import csv
import json
import re
from pathlib import Path

SRC = Path(
    r"C:\Users\Mohamed Saad\OneDrive - Amreyahcement\Desktop"
    r"\all_ijps_normalized_exports\structure"
)
OUT = Path(__file__).resolve().parent / "data" / "seed-new-structure.sql"

AREA_PREFIX = {
    "area_01_raw_mills": "RM",
    "area_02_by_pass_ep_and_rms_bag_filter": "BP",
    "area_03_kiln": "KLN",
}


def q(v: str) -> str:
    return "'" + (v or "").replace("'", "''") + "'"


def clean(v: str) -> str:
    return re.sub(r"\s+", " ", (v or "").replace("\n", " ")).strip()


def clean_task(text: str) -> str:
    # drop the trailing "Scheduled dates: ..." note, keep the actual check
    t = re.split(r"scheduled dates\s*:", text, flags=re.IGNORECASE)[0]
    return clean(t)


def classify(hay: str):
    h = hay.lower()

    def has(*w):
        return any(x in h for x in w)

    if has("lubric", "oil ", " oil", "grease", "gearbox", "gear box"):
        cat = "Lubrication"
    elif has("vibrat", "abnormal noise", "abnormal sound", "bearing"):
        cat = "Vibration"
    elif has("temperature", "temp "):
        cat = "Temperature"
    elif has("align"):
        cat = "Alignment"
    elif has("leak"):
        cat = "Leakage"
    elif has("earth", "cable", "electr", "motor "):
        cat = "Electrical"
    elif has("pressure", "sensor", "gauge", "instrument"):
        cat = "Instrumentation"
    elif has("clean", "dust", "housekeep"):
        cat = "Housekeeping"
    elif has("emission", "environment"):
        cat = "Environmental"
    elif has("wear", "crack", "worn", "deform", "broken", "bolt", "chain", "roller"):
        cat = "Wear"
    else:
        cat = "Visual"

    freq = {
        "Housekeeping": "Weekly",
        "Environmental": "Weekly",
        "Vibration": "Weekly",
        "Lubrication": "Monthly",
        "Wear": "Quarterly",
        "Alignment": "Quarterly",
        "Electrical": "Quarterly",
        "Instrumentation": "Quarterly",
    }.get(cat, "Monthly")
    prio = "High" if cat in ("Vibration", "Electrical") else "Medium"
    if cat in ("Electrical", "Instrumentation"):
        role = "Electrical Engineer"
    elif cat in ("Vibration", "Alignment", "Wear", "Lubrication"):
        role = "Mechanical Engineer"
    else:
        role = "Inspector"
    return cat, freq, prio, role


def read_csv(name):
    with open(SRC / name, encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def main():
    areas = read_csv("areas.csv")
    sections = read_csv("sections.csv")
    equipment = read_csv("equipment.csv")
    tasks = read_csv("tasks.csv")

    # group tasks by equipment_id (preserve order by task_sequence)
    tasks_by_eq: dict[str, list[str]] = {}
    for t in sorted(tasks, key=lambda r: (r["equipment_id"], int(r["task_sequence"]))):
        lab = clean_task(t["task_text"])
        if lab:
            tasks_by_eq.setdefault(t["equipment_id"], []).append(lab)

    # section code map + detect areas needing a fallback "general" section
    section_code: dict[str, str] = {}
    per_area_sec_idx: dict[str, int] = {}
    for s in sections:
        pfx = AREA_PREFIX[s["area_id"]]
        per_area_sec_idx[s["area_id"]] = per_area_sec_idx.get(s["area_id"], 0) + 1
        section_code[s["section_id"]] = f"{pfx}-SEC{per_area_sec_idx[s['area_id']]:02d}"

    areas_needing_general = {
        e["area_id"] for e in equipment if not e["section_id"].strip()
    }
    general_section_code = {a: f"{AREA_PREFIX[a]}-GEN" for a in areas_needing_general}

    sql: list[str] = []
    sql.append("-- CPIIS asset tree re-import from normalized IJP export")
    sql.append("-- Generated by scripts/import_new_structure.py; run after TRUNCATE.\n")

    # ── areas ──
    sql.append(
        "insert into public.areas (area_code, area_name) values\n"
        + ",\n".join(
            f"  ({q(AREA_PREFIX[a['area_id']])}, {q(clean(a['area_name']))})"
            for a in areas
        )
        + ";\n"
    )

    # ── sections (real + general fallbacks) ──
    sec_rows = []
    for s in sections:
        sec_rows.append(
            (section_code[s["section_id"]], AREA_PREFIX[s["area_id"]], clean(s["section_name"]))
        )
    for area_id, code in general_section_code.items():
        sec_rows.append((code, AREA_PREFIX[area_id], "معدات عامة"))
    sql.append(
        "insert into public.sections (section_code, area_id, section_name)\n"
        "select v.scode, a.area_id, v.sname from (values\n"
        + ",\n".join(f"  ({q(c)}, {q(ac)}, {q(n)})" for c, ac, n in sec_rows)
        + "\n) as v(scode, acode, sname)\n"
        "join public.areas a on a.area_code = v.acode;\n"
    )

    # ── equipment (unique code prefix+seq within area) ──
    eq_code: dict[str, str] = {}
    per_area_eq_idx: dict[str, int] = {}
    eq_rows = []
    for e in equipment:
        pfx = AREA_PREFIX[e["area_id"]]
        per_area_eq_idx[e["area_id"]] = per_area_eq_idx.get(e["area_id"], 0) + 1
        code = f"{pfx}-{per_area_eq_idx[e['area_id']]:03d}"
        eq_code[e["equipment_id"]] = code
        scode = (
            section_code.get(e["section_id"])
            if e["section_id"].strip()
            else general_section_code[e["area_id"]]
        )
        eq_rows.append(
            (scode, code, clean(e["equipment_name"]) or code, clean(e["functional_location"]))
        )
    sql.append(
        "insert into public.equipment (section_id, equipment_code, equipment_name, functional_location)\n"
        "select s.section_id, v.ecode, v.ename, nullif(v.floc, '') from (values\n"
        + ",\n".join(
            f"  ({q(sc)}, {q(ec)}, {q(en)}, {q(fl)})" for sc, ec, en, fl in eq_rows
        )
        + "\n) as v(scode, ecode, ename, floc)\n"
        "join public.sections s on s.section_code = v.scode;\n"
    )

    # ── one MAIN part per equipment ──
    part_rows = [(eq_code[e["equipment_id"]], clean(e["equipment_name"]) or eq_code[e["equipment_id"]]) for e in equipment]
    sql.append(
        "insert into public.equipment_parts (equipment_id, part_code, part_name, part_group, inspectable)\n"
        "select e.equipment_id, 'MAIN', v.pname, 'الماكينة', true from (values\n"
        + ",\n".join(f"  ({q(ec)}, {q(pn)})" for ec, pn in part_rows)
        + "\n) as v(ecode, pname)\n"
        "join public.equipment e on e.equipment_code = v.ecode;\n"
    )

    # ── one general activity per equipment that has check tasks ──
    act_rows = []
    for e in equipment:
        items = tasks_by_eq.get(e["equipment_id"])
        if not items:
            continue
        code = eq_code[e["equipment_id"]]
        cat, freq, prio, role = classify(clean(e["equipment_name"]) + " " + " ".join(items))
        checklist = json.dumps([{"label": it} for it in items], ensure_ascii=False)
        aname = (clean(e["equipment_name"]) or code) + " — فحص عام"
        act_rows.append((code, f"{code}-GEN", aname[:200], cat, freq, prio, role, checklist))

    sql.append(
        "with data(ecode, acode, aname, cat, freq, prio, role, checklist) as (values\n"
        + ",\n".join(
            f"  ({q(ec)}, {q(ac)}, {q(an)}, {q(c)}, {q(f)}, {q(p)}, {q(r)}, {q(cl)}::jsonb)"
            for ec, ac, an, c, f, p, r, cl in act_rows
        )
        + "\n)\n"
        "insert into public.inspection_activities\n"
        "  (equipment_part_id, activity_code, activity_name, inspection_category,\n"
        "   frequency_type, priority, responsible_role, standard_checklist)\n"
        "select ep.equipment_part_id, d.acode, d.aname, d.cat::public.inspection_category,\n"
        "       d.freq::public.frequency_type, d.prio::public.priority_level,\n"
        "       d.role::public.app_user_role, d.checklist\n"
        "from data d\n"
        "join public.equipment e on e.equipment_code = d.ecode\n"
        "join public.equipment_parts ep on ep.equipment_id = e.equipment_id and ep.part_code = 'MAIN';\n"
    )

    OUT.write_text("\n".join(sql), encoding="utf-8")
    print(
        f"areas={len(areas)} sections={len(sec_rows)} equipment={len(eq_rows)} "
        f"parts={len(part_rows)} activities={len(act_rows)} -> {OUT.name}"
    )


if __name__ == "__main__":
    main()
