"""
Phase 2 seed: turn the real IJP checklists into inspection_activities.

For each equipment, every bold "part" row that is directly followed by one or
more non-bold checklist lines becomes one inspection_activity bound to that
equipment_part, carrying those lines as its standard_checklist. Category,
frequency, priority and responsible role are inferred from keywords.

Part-code resolution replicates import_equipment.py exactly (same slugify +
per-equipment dedup order) so activities resolve to the right equipment_part.

Emits scripts/data/seed-phase2-activities.sql (idempotent via ON CONFLICT).
Run:  python scripts/seed_inspection_activities.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "scripts/data/raw-equipment-checklists.json"
OUT = ROOT / "scripts/data/seed-phase2-activities.sql"


def slugify(text: str, max_len: int = 50) -> str:
    text = text.upper()
    text = re.sub(r"[^A-Z0-9]+", "-", text).strip("-")
    return text[:max_len] or "PART"


def sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def classify(part_name: str, items: list[str]) -> tuple[str, str, str, str]:
    """Return (category, frequency_type, priority, responsible_role)."""
    hay = (part_name + " " + " ".join(items)).lower()

    def has(*words: str) -> bool:
        return any(w in hay for w in words)

    if has("lubric", "oil ", " oil", "grease", "lubrication"):
        category = "Lubrication"
    elif has("vibrat", "abnormal noise", "abnormal sound", "abnorml"):
        category = "Vibration"
    elif has("temperature", "temp "):
        category = "Temperature"
    elif has("align"):
        category = "Alignment"
    elif has("leak"):
        category = "Leakage"
    elif has("earth", "cable", "electr", "motor "):
        category = "Electrical"
    elif has("pressure", "sensor", "gauge", "instrument"):
        category = "Instrumentation"
    elif has("clean", "dust", "housekeep"):
        category = "Housekeeping"
    elif has("emission", "environment"):
        category = "Environmental"
    elif has("wear", "crack", "worn", "deform", "broken", "integrity", "missed", "bolt"):
        category = "Wear"
    else:
        category = "Visual"

    frequency = {
        "Housekeeping": "Weekly",
        "Environmental": "Weekly",
        "Vibration": "Weekly",
        "Lubrication": "Monthly",
        "Wear": "Quarterly",
        "Alignment": "Quarterly",
        "Electrical": "Quarterly",
        "Instrumentation": "Quarterly",
    }.get(category, "Monthly")

    priority = "High" if category in ("Vibration", "Electrical") else "Medium"

    if category in ("Electrical", "Instrumentation"):
        role = "Electrical Engineer"
    elif category in ("Vibration", "Alignment", "Wear", "Lubrication"):
        role = "Mechanical Engineer"
    else:
        role = "Inspector"

    return category, frequency, priority, role


def main() -> None:
    blocks = json.loads(RAW.read_text(encoding="utf-8"))
    values: list[str] = []

    for block in blocks:
        has_name = bool(block["raw_name"].strip())
        equip_code = slugify(block["raw_name"]) if has_name else f"UNSPECIFIED-{block['num']}"

        rows = block["rows"]
        seen_codes: dict[str, int] = {}
        for j, r in enumerate(rows):
            if not r["bold"]:
                continue
            # replicate the exact part_code assigned during Phase 1 import
            base = slugify(r["text"])
            n = seen_codes.get(base, 0) + 1
            seen_codes[base] = n
            part_code = base if n == 1 else f"{base}-{n}"

            # collect this part's direct checklist lines
            items: list[str] = []
            k = j + 1
            while k < len(rows) and not rows[k]["bold"]:
                items.append(rows[k]["text"])
                k += 1
            if not items:
                continue

            category, frequency, priority, role = classify(r["text"], items)
            activity_code = f"{equip_code}-{part_code}"[:80]
            activity_name = r["text"][:200]
            checklist = json.dumps([{"label": it} for it in items], ensure_ascii=False)

            values.append(
                "  ("
                f"{sql_str(equip_code)}, {sql_str(part_code)}, {sql_str(activity_code)}, "
                f"{sql_str(activity_name)}, {sql_str(category)}, {sql_str(frequency)}, "
                f"{sql_str(priority)}, {sql_str(role)}, {sql_str(checklist)}::jsonb"
                ")"
            )

    sql = []
    sql.append("-- Phase 2 seed: inspection_activities from real IJP checklists")
    sql.append("-- Generated by scripts/seed_inspection_activities.py; do not hand-edit.")
    sql.append(
        "with data(ecode, pcode, acode, aname, cat, freq, prio, role, checklist) as (\n  values"
    )
    sql.append(",\n".join(values))
    sql.append(")")
    sql.append(
        "insert into public.inspection_activities\n"
        "  (equipment_part_id, activity_code, activity_name, inspection_category,\n"
        "   frequency_type, priority, responsible_role, standard_checklist)\n"
        "select ep.equipment_part_id, d.acode, d.aname, d.cat::public.inspection_category,\n"
        "       d.freq::public.frequency_type, d.prio::public.priority_level,\n"
        "       d.role::public.app_user_role, d.checklist\n"
        "from data d\n"
        "join public.equipment e on e.equipment_code = d.ecode\n"
        "join public.equipment_parts ep\n"
        "  on ep.equipment_id = e.equipment_id and ep.part_code = d.pcode\n"
        "on conflict (equipment_part_id, activity_code) do nothing;"
    )

    OUT.write_text("\n".join(sql), encoding="utf-8")
    print(f"Wrote {OUT.name} with {len(values)} inspection_activities")


if __name__ == "__main__":
    main()
