-- Batch three: the conveyor running gear -- drums, sprockets, chains, rims --
-- taking the dictionary to 60.7% of all checklist items.
--
-- Drive and driven are distinguished throughout ("درام القيادة" against "الدرام
-- المنقاد"), because on a conveyor the pair carry the same checks and only their
-- position tells them apart. Collapsing them would make the sheet ambiguous at
-- exactly the point where it is telling the fitter which end to walk to.

insert into public.checklist_translations (label_norm, label_en, label_ar)
select public.checklist_label_norm(v.en), v.en, v.ar
from (values
  ('Safety: Dismantel the Screw conveyor coupling covers.', 'السلامة: فك أغطية كوبلينج البريمة'),
  ('Safety: Measure the clearance of the bearings and record it as the photo below represents.', 'السلامة: قِس خلوص البيرنجات وسجّله زي ما الصورة اللي تحت موضحة'),
  ('Safety: Measure the thinckness of the spiral and record it as the photo below represents.', 'السلامة: قِس سُمك ريشة البريمة وسجّله زي ما الصورة اللي تحت موضحة'),
  ('Counter weight: Check the condition of safety wire.', 'الثقل الموازن: افحص حالة سلك الأمان'),
  ('Gear Box: Check oil level.', 'الجير بوكس: افحص منسوب الزيت'),
  ('Gear Box.(Geard Motor).: Check oil level.', 'الجير بوكس (الموتور المدمج): افحص منسوب الزيت'),
  ('Bending drum 01: Check the wear of the coating', 'درام الانحناء 01: افحص تآكل التغليف'),
  ('Bending drum 02: Check the wear of the coating', 'درام الانحناء 02: افحص تآكل التغليف'),
  ('Counter weight: Check the condition of foundation.', 'الثقل الموازن: افحص حالة القاعدة'),
  ('Driven sprocket: Check the grease leakage', 'الترس المنقاد: افحص تسريب الشحم'),
  ('Casing: Check the gland seal packing.(stuffing box) at drive drum side.', 'الجسم: افحص حشو الجلاند (الستافينج بوكس) جهة درام القيادة'),
  ('Discharge chute: Check the material leakage', 'شوت التفريغ: افحص تسريب المادة'),
  ('Drive sprocket: Check the abnormal noise.', 'الترس القائد: افحص وجود صوت غير طبيعي'),
  ('Inlet chute: Check side defleclector wear', 'شوت الدخول: افحص تآكل الموجّه الجانبي'),
  ('Outlet chute: Check impact wall deflector', 'شوت الخروج: افحص موجّه حائط الصدم'),
  ('Rollers: Check the Lower return rollers steel and rubber (noise, missing, stuck).', 'الرولات: افحص رولات الرجوع السفلية الحديد والكاوتش (صوت، مفقود، متعلّق)'),
  ('Rollers: Check the upper carrier roller steel and impact (noise, missing, stuck).', 'الرولات: افحص رولات الحمل العلوية الحديد ورولات الصدم (صوت، مفقود، متعلّق)'),
  ('Structre: Check the beam Fixation.', 'الهيكل: افحص تثبيت الكمرات'),
  ('Tension drum: Check the wear of the coating', 'درام الشد: افحص تآكل التغليف'),
  ('Gear Box: Check oil level and temperature.', 'الجير بوكس: افحص منسوب الزيت والحرارة'),
  ('Kiln tyre with splined fastening system.: Check the condition of wedges ( loss, missed, broken).', 'طوق الفرن بنظام التثبيت المشرشر: افحص حالة الأسافين (سايبة، مفقودة، مكسورة)'),
  ('Measuring Procedure: Record the measurement in the table below', 'خطوات القياس: سجّل القراءة في الجدول اللي تحت'),
  ('Casing.: Check condition of the links through the inspection door ( wear, deformation.', 'الجسم: افحص حالة وصلات الجنزير من باب التفتيش (تآكل، اعوجاج)'),
  ('Casing.: Check the wear of sliding guide through the inspection door.', 'الجسم: افحص تآكل موجّه الانزلاق من باب التفتيش'),
  ('Drive drum: Check the bearing housing seals and grease leakage.', 'درام القيادة: افحص سيلات بيت البيرنج وتسريب الشحم'),
  ('Drive drum: Check the grease leakage', 'درام القيادة: افحص تسريب الشحم'),
  ('Drive sprocket 1 (big): Check the bearing housing seals and grease leakage.', 'الترس القائد 1 (الكبير): افحص سيلات بيت البيرنج وتسريب الشحم'),
  ('Drive sprocket 2 .Aux-(small).: Check the bearing housing seals and grease leakage.', 'الترس القائد 2 المساعد (الصغير): افحص سيلات بيت البيرنج وتسريب الشحم'),
  ('Structre: Check the condition of drag chain foundation.', 'الهيكل: افحص حالة قاعدة الدراج تشين'),
  ('Check the condition of fastening.', 'افحص حالة التثبيت'),
  ('Check the condtion of corrosion.', 'افحص حالة الصدأ'),
  ('Drive drum: Check the abnormal noise.', 'درام القيادة: افحص وجود صوت غير طبيعي'),
  ('Drive drum: Check the drum integrity.', 'درام القيادة: افحص سلامة الدرام'),
  ('Driven drum: Check the abnormal noise.', 'الدرام المنقاد: افحص وجود صوت غير طبيعي'),
  ('Flex-Joint: Check the condition of flex-joint (cut, tear, material blockage in the joint).', 'الوصلة المرنة: افحص حالتها (قطع، تهتك، انسداد بالمادة)'),
  ('Measuring procedure: Record all data in the table.', 'خطوات القياس: سجّل كل البيانات في الجدول'),
  ('Review the coupling cover fixation between Motor and fan.', 'راجع تثبيت غطاء الكوبلينج بين الموتور والمروحة'),
  ('Rollers: Check if material sticking on the rollers.', 'الرولات: افحص التصاق المادة على الرولات'),
  ('Driven drum: Check the bearing housing seals and grease leakage.', 'الدرام المنقاد: افحص سيلات بيت البيرنج وتسريب الشحم'),
  ('Driven drum: Check the grease leakage', 'الدرام المنقاد: افحص تسريب الشحم'),
  ('Driven sprocket: Check the sprocket integrity.', 'الترس المنقاد: افحص سلامة الترس'),
  ('Measuring procedure: SYMBLE', 'خطوات القياس: الرمز'),
  ('Chain: Check the counter weight integrity.', 'الجنزير: افحص سلامة الثقل الموازن'),
  ('Check the abnormal noise by test working.', 'افحص وجود صوت غير طبيعي بالتشغيل التجريبي'),
  ('Check the Motor temperature by test working.', 'افحص حرارة الموتور بالتشغيل التجريبي'),
  ('Discharge chute: Check the condition of wear inlet chute', 'شوت التفريغ: افحص حالة تآكل شوت الدخول'),
  ('Discharge chute: Check the fixation of discharge pipe that feed material out of the Mill.', 'شوت التفريغ: افحص تثبيت ماسورة التفريغ اللي بتخرج المادة من الطاحونة'),
  ('Discharge chute: Check the liner missing , corrosion.', 'شوت التفريغ: افحص البطانة الناقصة والصدأ'),
  ('Drive sprocket: Check the bearing temprature.', 'الترس القائد: افحص حرارة البيرنج'),
  ('Measuring procedure: Put the template and review the wear.', 'خطوات القياس: ضع الشابلونة وراجع التآكل'),
  ('Rotay Bearing. DE: Check the bearing housing seals and grease leakage.', 'بيرنج الروتاري جهة القيادة (DE): افحص سيلات بيت البيرنج وتسريب الشحم'),
  ('Rotay Bearing. DE: Check the grease leakage', 'بيرنج الروتاري جهة القيادة (DE): افحص تسريب الشحم'),
  ('Rotay Bearing. NDE: Check the bearing housing seals and grease leakage.', 'بيرنج الروتاري الجهة الحرة (NDE): افحص سيلات بيت البيرنج وتسريب الشحم'),
  ('Rotay Bearing. NDE: Check the bearing temprature.', 'بيرنج الروتاري الجهة الحرة (NDE): افحص حرارة البيرنج'),
  ('Rotay Bearing. NDE: Check the grease leakage', 'بيرنج الروتاري الجهة الحرة (NDE): افحص تسريب الشحم'),
  ('Aux-Gear box: Check colour and visual aspect of oil.', 'الجير بوكس المساعد: افحص لون الزيت ومظهره'),
  ('Aux-Gear box: Check gear box condition and mounting.', 'الجير بوكس المساعد: افحص حالة الجير بوكس وتثبيته'),
  ('Chain: Check the abnormal noise.', 'الجنزير: افحص وجود صوت غير طبيعي'),
  ('Driven drum: Check the drum integrity.', 'الدرام المنقاد: افحص سلامة الدرام'),
  ('Measuring procedure: Close the inspection door again.', 'خطوات القياس: اقفل باب التفتيش تاني'),
  ('Safety: Measure the thickness of the belt sections listed above using a mm meter', 'السلامة: قِس سُمك أجزاء السير المذكورة فوق بجهاز قياس بالمليمتر'),
  ('Aux-Gear box: Check condition of gear box breather.', 'الجير بوكس المساعد: افحص حالة فتحة التنفس'),
  ('Chain: Check the chain elongation', 'الجنزير: افحص استطالة الجنزير'),
  ('check casing', 'افحص الجسم'),
  ('Check the condition beams.', 'افحص حالة الكمرات'),
  ('Check the condition of the walkways.', 'افحص حالة الممرات'),
  ('Check the Motor tempature.', 'افحص حرارة الموتور'),
  ('Drive rim: Check the abnormal noise.', 'الطوق القائد: افحص وجود صوت غير طبيعي'),
  ('Drive rim: Check the bearing housing seals and grease leakage.', 'الطوق القائد: افحص سيلات بيت البيرنج وتسريب الشحم'),
  ('Driven rim: Check the abnormal noise.', 'الطوق المنقاد: افحص وجود صوت غير طبيعي')
) as v(en, ar)
on conflict (label_norm) do update
set label_en = excluded.label_en, label_ar = excluded.label_ar, updated_at = now();
