-- First words into the dictionary: the sixty sentences a fitter meets most
-- often, which between them are 37% of all 16,304 checklist items. The two at
-- the top alone -- the lighting check and the guardrails check -- appear 703
-- times each, on nearly every plan in the plant.
--
-- Translated by frequency rather than by line, because line 1 and line 3 share
-- their commonest items: 262 sentences are on both, and they are the busiest
-- ones. Sorting by frequency serves both lines at once.
--
-- The wording is the plant's own, not the dictionary's. A fitter here says
-- "جير بوكس", "بيرنج", "شوت", "إير سلايد" -- so those stay as they are said.
-- Translating them into formal Arabic ("صندوق تروس", "محمل") would be correct
-- and useless. The component prefix is kept as a prefix so a man scanning a
-- sheet can still find his way down it by component.
--
-- label_norm is computed, not written, so a typo in the English below makes a
-- row that matches nothing rather than a row that matches the wrong thing.

insert into public.checklist_translations (label_norm, label_en, label_ar)
select public.checklist_label_norm(v.en), v.en, v.ar
from (values
  ('Safety: Check condition of access, guardrails, housings, ladders, emergency stops',
   'السلامة: افحص حالة مداخل الوصول والدرابزين والأغطية والسلالم ومفاتيح الطوارئ'),
  ('Safety: Check lighting',
   'السلامة: افحص الإضاءة'),
  ('Environment: Cleaning of the equipement and around.',
   'البيئة: نظافة المعدة والمنطقة حواليها'),
  ('Environment: Condition of dust emission.',
   'البيئة: حالة تسرب الأتربة'),
  ('Safety: Check protections for nips and moving parts',
   'السلامة: افحص واقيات الأجزاء المتحركة ومواضع الانحشار'),
  ('Casing: Check inspection doors (seal, tightening).',
   'الجسم: افحص أبواب التفتيش (الحشو والربط)'),
  ('Inlet chute: Check condition of wear.',
   'شوت الدخول: افحص حالة التآكل'),
  ('outlet chute: Check condition of wear.',
   'شوت الخروج: افحص حالة التآكل'),
  ('Structre: Check the condition beams.',
   'الهيكل: افحص حالة الكمرات'),
  ('Structre: Check the condition of the walkways.',
   'الهيكل: افحص حالة الممرات'),
  ('Structre: Check the condition side rail.',
   'الهيكل: افحص حالة الحاجز الجانبي'),
  ('Casing: Check casing condition (holes, deformation , wear , cracks…).',
   'الجسم: افحص حالة الجسم (خروم، اعوجاج، تآكل، شروخ)'),
  ('Casing: Check for material leakage.',
   'الجسم: افحص تسريب المادة'),
  ('Safety: Check earthing cables and connectors',
   'السلامة: افحص كابلات الأرضي والوصلات'),
  ('Safety: Check general condition of emergency stops',
   'السلامة: افحص الحالة العامة لمفاتيح الطوارئ'),
  ('Casing: Check the cover bolts tightening.',
   'الجسم: افحص ربط مسامير الغطاء'),
  ('Casing: Check casing condition (holes, dents…).',
   'الجسم: افحص حالة الجسم (خروم، دعكات)'),
  ('Casing: Check for water in-leakage, condensation.',
   'الجسم: افحص تسرب المياه للداخل والتكثيف'),
  ('Casing: Check sight glass (seal, tightening, cracks, ….).',
   'الجسم: افحص زجاج الرؤية (الحشو، الربط، الشروخ)'),
  ('Fan Bearing: Check the bearing housing seals and grease leakage.',
   'بيرنج المروحة: افحص سيلات بيت البيرنج وتسريب الشحم'),
  ('Fan casing: Check the condtion of worn-out, corrosion, fastening.',
   'جسم المروحة: افحص حالة التآكل والصدأ والتثبيت'),
  ('Pipes: Check adjustment of air regulator valve.',
   'المواسير: افحص ضبط محبس تنظيم الهواء'),
  ('Pipes: Check pipes and supports ,and check the flex joint (cut, tear, material leakage).',
   'المواسير: افحص المواسير وحواملها والوصلة المرنة (قطع، تهتك، تسريب مادة)'),
  ('Pipes: Check ventilation efficiency (negative pressure from inspection door).',
   'المواسير: افحص كفاءة التهوية (الضغط السالب من باب التفتيش)'),
  ('Gear Box: Check seal tightness',
   'الجير بوكس: افحص إحكام السيلات'),
  ('Safety: Check protections moving parts',
   'السلامة: افحص واقيات الأجزاء المتحركة'),
  ('Gear Box: Check gear box condition and mounting',
   'الجير بوكس: افحص حالة الجير بوكس وتثبيته'),
  ('Casing: Check the gland seal packing.(stuffing box).',
   'الجسم: افحص حشو الجلاند (الستافينج بوكس)'),
  ('Inlet chute: Check condition of corrosion.',
   'شوت الدخول: افحص حالة الصدأ'),
  ('Outlet chute: Check condition of corrosion.',
   'شوت الخروج: افحص حالة الصدأ'),
  ('Casing: Check the abnormal noise.',
   'الجسم: افحص وجود صوت غير طبيعي'),
  ('Gear Box: Check condition of gear box breather.',
   'الجير بوكس: افحص حالة فتحة تنفس الجير بوكس'),
  ('Casing: Check the condition of isolation.',
   'الجسم: افحص حالة العزل'),
  ('Inlet chute: Check the liner missing.',
   'شوت الدخول: افحص وجود بطانة ناقصة'),
  ('Gear Box.(Geard Motor): Check colour and visual aspect of oil.',
   'الجير بوكس (الموتور المدمج): افحص لون الزيت ومظهره'),
  ('Gear Box.(Geard Motor): Check condition of gear box breather.',
   'الجير بوكس (الموتور المدمج): افحص حالة فتحة التنفس'),
  ('Gear Box.(Geard Motor): Check gear box condition and mounting.',
   'الجير بوكس (الموتور المدمج): افحص حالة الجير بوكس وتثبيته'),
  ('Gear Box.(Geard Motor): Check seal tightness.',
   'الجير بوكس (الموتور المدمج): افحص إحكام السيلات'),
  ('Gear Box: Check colour and visual aspect of oil',
   'الجير بوكس: افحص لون الزيت ومظهره'),
  ('Outlet chute: Check the liner missing.',
   'شوت الخروج: افحص وجود بطانة ناقصة'),
  ('Measuring procedure: Close the bearing housing.',
   'خطوات القياس: اقفل بيت البيرنج'),
  ('Measuring procedure: Measure the clearance of the bearing and record it.',
   'خطوات القياس: قِس خلوص البيرنج وسجّل القراءة'),
  ('Measuring procedure: Open the bearing housing.',
   'خطوات القياس: افتح بيت البيرنج'),
  ('Safety: Clean very well all the material.',
   'السلامة: نظّف كل المادة كويس جدًا'),
  ('Measuring procedure: Clean very well the grease.',
   'خطوات القياس: نظّف الشحم كويس جدًا'),
  ('Safety: Close all the Screw conveyor covers very well.',
   'السلامة: اقفل كل أغطية البريمة كويس جدًا'),
  ('Safety: Open the Screw conveyor covers.',
   'السلامة: افتح أغطية البريمة'),
  ('Casing: Check overall condition corrosion.',
   'الجسم: افحص الحالة العامة للصدأ'),
  ('Driven sprocket: Check the bearing housing seals and grease leakage.',
   'الترس المنقاد: افحص سيلات بيت البيرنج وتسريب الشحم'),
  ('Fan casing: Check abnormal noise.',
   'جسم المروحة: افحص وجود صوت غير طبيعي'),
  ('Measuring procedure: Reagrease the bearing and put the seals.',
   'خطوات القياس: أعد تشحيم البيرنج وركّب السيلات'),
  ('Casing: Check bolt tightening.',
   'الجسم: افحص ربط المسامير'),
  ('Casing: Check bolts tightening.',
   'الجسم: افحص ربط المسامير'),
  ('Casing: Check for air leaks.',
   'الجسم: افحص تسريب الهواء'),
  ('Casing: Check for any scrap or metal parts inside the air slid.',
   'الجسم: افحص وجود خردة أو أجزاء معدنية جوه الإير سلايد'),
  ('Casing: Check if material flow is continuous (sight glass/inspection door).',
   'الجسم: افحص إن سريان المادة مستمر (من زجاج الرؤية أو باب التفتيش)'),
  ('Casing: Check if there is material leakage.',
   'الجسم: افحص وجود تسريب مادة'),
  ('Casing: Check overall condition corrosion and wear.',
   'الجسم: افحص الحالة العامة للصدأ والتآكل'),
  ('Casing: Check the condition of porous cloth, cut, blockage, tears, holes, screen.',
   'الجسم: افحص حالة القماش المسامي (قطع، انسداد، تهتك، خروم، الشبكة)'),
  ('Fan Bearing: Check the abnormal noise.',
   'بيرنج المروحة: افحص وجود صوت غير طبيعي')
) as v(en, ar)
on conflict (label_norm) do update
set label_en = excluded.label_en,
    label_ar = excluded.label_ar,
    updated_at = now();
